### ISSUE TITLE
Should we archive this feedstock?

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/xlayers-feedstock#19]
### Comment:

@conda-forge/xlayers team, looks like this package is deprecated. See https://github.com/cspencerjones/xlayers/commit/3de42772deec1121398af00f41277c6986fd354b

Should we archive it?

**Comment by cspencerjones** [comment]
Yes - that would be great. Can you do this on your own or do you need me to do something?

**Comment by ocefpaf** [comment]
I can do that for you. It is just a PR to our admin-requests repository. Thanks for confirming. I know that maintaining Fortran extensions is quite laborious lately but at least we have that functionality elsewhere. Thanks for keeping this package alive for as long as you did!
